version: "3.9"
services:
  api:
    image: api
    deploy:
      replicas: 3
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/test?authSource=admin&readPreference=primary&ssl=false
      MONGO_DATABASE: demo
      REDIS_URI: redis:6379
    networks:
      - api_network
    external_links:
      - mongodb
      - redis
  redis:
    image: redis:7.2
    networks:
      - api_network
    ports:
      - 6379:6379
    volumes:
      - $PWD/conf/redis.conf:/usr/local/etc/redis/redis.conf
  mongodb:
    image: mongo:4.4.24
    networks:
      - api_network
    ports:
      - 27017:27017
    volumes:
      - $PWD/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  import:
    image: mongo:4.4.24
    networks:
      - api_network
    volumes:
      - $PWD/data:/data/db
      - $PWD/conf/recipes.json:/tmp/recipes.json
    command: mongoimport -h mongodb:27017 -u admin -p password --authenticationDatabase admin -d demo -c recipes --jsonArray --file /tmp/recipes.json --drop
    depends_on:
      - mongodb
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - $PWD/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - api_network

networks:
  api_network: